export { default as NavBar } from './NavBar';
export { default as Footer } from './Footer';
export { default as AnimatedWave } from './AnimatedWave';
export { default as HeroSection } from './HeroSection';
export { default as SectionOne } from './SectionOne';
export { default as SectionTwo } from './SectionTwo';
export { default as SectionThree } from './SectionThree';
export { default as SectionFour } from './SectionFour';
export { default as DownloadSection } from './DownloadSection';
